/**
 * 构建沙箱裁判脚本，在 iframe 中注入以劫持和检测攻击行为。
 * 注意事项：所有 JavaScript 代码必须避免使用可能破坏脚本标签的语法。
 * 使用简单字符串操作，避免复杂正则。
 */
export function buildJudgeScript(attackPayload?: string): string {
  const safePayload = JSON.stringify(attackPayload ?? '');

  const lines: string[] = [
    '(function() {',
    '  "use strict";',
    '',
    '  var _payload = ' + safePayload + ';',
    '  var _reported = false;',
    '',
    '  function _report(type, data) {',
    '    window.parent.postMessage({ type: type, source: "sandbox", ts: Date.now(), data: data }, "*");',
    '  }',
    '',
    '  /* 1. 劫持 alert / prompt / confirm */',
    '  var _alert = window.alert;',
    '  window.alert = function(msg) {',
    '    var s = String(msg);',
    '    var isIdor = s.indexOf("越权") !== -1 || s.indexOf("IDOR") !== -1;',
    '    _report("ATTACK_DETECTED", { attackType: isIdor ? "idor" : "xss", vector: isIdor ? "unauthorized-access" : "alert", detail: s });',
    '    if (_alert) _alert.call(window, msg);',
    '  };',
    '',
    '  var _prompt = window.prompt;',
    '  window.prompt = function(msg) {',
    '    _report("ATTACK_DETECTED", { attackType: "xss", vector: "prompt", detail: String(msg) });',
    '    return _prompt ? _prompt.call(window, msg) : null;',
    '  };',
    '',
    '  var _confirm = window.confirm;',
    '  window.confirm = function(msg) {',
    '    _report("ATTACK_DETECTED", { attackType: "xss", vector: "confirm", detail: String(msg) });',
    '    return _confirm ? _confirm.call(window, msg) : false;',
    '  };',
    '',
    '  /* 2. 脚本错误捕获 */',
    '  window.onerror = function(msg, source, line, col, err) {',
    '    _report("SCRIPT_ERROR", { message: String(msg), source: source, line: line, col: col });',
    '    return true;',
    '  };',
    '',
    '  /* 3. MOCK_DB */',
    '  window.MOCK_DB = {',
    '    users: [',
    '      { id: 1, username: "admin", email: "admin@secvibe.test", role: "管理员" },',
    '      { id: 2, username: "alice", email: "alice@secvibe.test", role: "普通用户" },',
    '      { id: 3, username: "bob", email: "bob@secvibe.test", role: "普通用户" },',
    '      { id: 4, username: "charlie", email: "charlie@secvibe.test", role: "普通用户" },',
    '    ],',
    '    query: function(sql) {',
    '      var lower = (sql || "").toLowerCase();',
    '      _report("SQL_QUERY", { sql: sql });',
    '      var hasInjection = lower.indexOf(" or ") !== -1 ||',
    '        lower.indexOf("1=1") !== -1 ||',
    '        lower.indexOf("union") !== -1;',
    '      if (hasInjection) {',
    '        _report("ATTACK_DETECTED", { attackType: "sqli", vector: "pattern", detail: sql });',
    '        return this.users;',
    '      }',
    '      /* 尝试提取 ID 数字 */',
    '      var parts = sql.split("id =");',
    '      if (parts.length === 2) {',
    '        var val = parts[1].trim().split(/\\s/)[0].replace(/[^0-9]/g, "");',
    '        if (val) {',
    '          var num = parseInt(val, 10);',
    '          return this.users.filter(function(u) { return u.id === num; });',
    '        }',
    '      }',
    '      return [];',
    '    },',
    '  };',
    '',
    '  /* 4. MutationObserver — 仅在攻击激活时检测 */',
    '  if (_payload) {',
    '    try {',
    '      (function() {',
    '        var obs = new MutationObserver(function(ms) {',
    '          for (var mi = 0; mi < ms.length; mi++) {',
    '            if (ms[mi].type !== "childList") continue;',
    '            for (var ni = 0; ni < ms[mi].addedNodes.length; ni++) {',
    '              var n = ms[mi].addedNodes[ni];',
    '              if (n.nodeType !== 1) continue;',
    '              (function walk(el) {',
    '                if (!el || !el.getAttribute) return;',
    '                var a = el.getAttribute("onerror") || el.getAttribute("onload");',
    '                if (a) _report("ATTACK_DETECTED", { attackType: "dom-xss", vector: "attribute-injection", detail: a });',
    '                for (var ci = 0; ci < el.children.length; ci++) walk(el.children[ci]);',
    '              })(n);',
    '            }',
    '          }',
    '        });',
    '        obs.observe(document.documentElement, { childList: true, subtree: true });',
    '      })();',
    '    } catch(e) {}',
    '  }',
    '',
    '  /* 5. 全局攻击载荷 */',
    '  if (_payload) {',
    '    window.__ATTACK_PAYLOAD__ = _payload;',
    '    var _origGet = URLSearchParams.prototype.get;',
    '    URLSearchParams.prototype.get = function(k) {',
    '      if (k === "msg" || k === "comment" || k === "q" || k === "input") return _payload;',
    '      return _origGet.call(this, k);',
    '    };',
    '  }',
    '',
    '  _report("SANDBOX_READY", {});',
    '})();',
  ];

  return '<script>' + lines.join('\n') + '<' + '/script>';
}
